In [125]:
import pandas as pd
import numpy as np
import seaborn as sns

expenses = pd.read_excel (r'C:\Users\LAKSHYA\Downloads\STRBI_Table_No._02___Earnings_and_Expenses_of_Scheduled_Commercial_Banks.xlsx',sheet_name='EXPENSES')
returns = pd.read_excel (r'C:\Users\LAKSHYA\Downloads\STRBI_Table_No._02___Earnings_and_Expenses_of_Scheduled_Commercial_Banks.xlsx',sheet_name='Returns')

In [126]:
expenses.replace('-',np.nan, inplace=True)
Y=returns.iloc[:,:]

expenses=pd.concat([expenses,Y],axis=1)

In [128]:
expenses

Banks  Interest on deposits  \
0                     BANK OF BARODA          37564.403900   
1                      BANK OF INDIA          24482.289402   
2                BANK OF MAHARASHTRA           6525.948300   
3                        CANARA BANK          42096.959900   
4              CENTRAL BANK OF INDIA          13994.073500   
...                              ...                   ...   
1489                    SHINHAN BANK              1.233300   
1490  SOCIETE GENERALE                           19.845100   
1491  SONALI BANK                                 0.668200   
1492  STANDARD CHARTERED BANK                   700.369900   
1493                       UFJ BANK               1.441700   

      Interest on RBI/ Inter - bank borrowings       Others  \
0                                  1863.767900  2257.864100   
1                                  1155.891038   691.422711   
2                                    49.650600   395.469300   
3                                  1057.893300  2022.770500   
4                                     3.256400   487.859900   
...                                        ...          ...   
1489                                  0.131200     1.519300   
1490                                  1.718800     0.002000   
1491                                       NaN     0.138100   
1492                                177.674100   229.403700   
1493                                  0.012500     0.535100   

      Payments to and provisions for employees  Rent, taxes and lighting  \
0                                 11445.530300               1505.920100   
1                                  6472.989995                751.822917   
2                                  2255.210400                218.233200   
3                                 12689.959400               1120.147900   
4                                  4141.306300                494.080700   
...                                        ...                       ...   
1489                                  1.197200                  1.009800   
1490                                  7.540700                  1.204400   
1491                                  1.600400                  0.562000   
1492                                285.777600                 43.818600   
1493                                  2.108100                  1.677800   

      Printing and stationery  Advertisement and publicity  \
0                  126.301800                    87.085600   
1                   64.668211                     7.543886   
2                   17.681500                    39.287400   
3                  133.620900                    42.135800   
4                   26.540000                     4.786400   
...                       ...                          ...   
1489                 0.055400                     0.012200   
1490                 0.120100                     0.009600   
1491                 0.051200                     0.017300   
1492                28.476900                    39.883100   
1493                 0.124700                     0.006400   

      Depreciation on bank's property  \
0                         1314.541700   
1                          372.203917   
2                          188.111200   
3                          820.169000   
4                          292.318700   
...                               ...   
1489                         0.263500   
1490                         3.260100   
1491                         0.037500   
1492                        26.838000   
1493                         0.562500   

      Directors' fees, allowances and expenses  Auditors' fees and expenses  \
0                                      1.22460                    73.866300   
1                                      0.42946                    80.291636   
2                                      0.33460                    19.591800   
3                                      0.82320                

In [129]:
expenses_missing=expenses.isna()
expenses_missing.mean()*100


Banks                                        0.000000
Interest on deposits                         1.874163
Interest on RBI/ Inter - bank borrowings     5.354752
Others                                      18.607764
Payments to and provisions for employees     0.334672
Rent, taxes and lighting                     0.066934
Printing and stationery                      0.066934
Advertisement and publicity                  3.480589
Depreciation on bank's property              0.200803
Directors' fees, allowances and expenses    40.495315
Auditors' fees and expenses                  0.133869
Law charges                                  4.685408
Postage, telegrams, telephones, etc          0.200803
Repairs and maintenance                      0.669344
Insurance                                    0.669344
Other expenditure                            0.000000
Provisions and Contingencies                 0.000000
Total income                                 0.000000
dtype: float64

In [130]:
expenses.drop(["Directors' fees, allowances and expenses","Others"],axis=1,inplace=True)

In [131]:
expenses.dropna(inplace=True)

In [135]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Interest on deposits']).reshape(-1,1)

array([[3.76e+04],
       [2.45e+04],
       [6.53e+03],
       ...,
       [1.98e+01],
       [7.00e+02],
       [1.44e+00]])

In [136]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [138]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9681077086698848
[2.]


In [139]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Interest on RBI/ Inter - bank borrowings']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.6297609374920138
[23.78]


In [140]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Payments to and provisions for employees']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9050472620557135
[7.86]


In [141]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Provisions and Contingencies']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9004219758865829
[4.48]


In [150]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Advertisement and publicity']).reshape(-1,1)
f = lambda x: x ** 2

X_2 = f(X)
X=np.concatenate((X,X_2),axis=1)
f = lambda x: x ** 3

X_3 = f(X)
X=np.concatenate((X,X_3),axis=1)


x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.35750604026082966
[ 2.83e+02  1.98e-01 -1.08e-03  7.42e-13]


In [151]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Rent, taxes and lighting']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.967353083192635
[55.93]


In [152]:
Y=expenses.iloc[:,-1].values
X=np.array(expenses['Auditors\' fees and expenses']).reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.6985397620228282
[853.83]


In [153]:
X_id=np.array(expenses['Interest on deposits']).reshape(-1,1)
X_pc=np.array(expenses['Provisions and Contingencies']).reshape(-1,1)
X_pe=np.array(expenses['Payments to and provisions for employees']).reshape(-1,1)
X=np.concatenate((X_id,X_pc,X_pe),axis=1)
Y=expenses.iloc[:,-1].values
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.score(x_test,y_test))
print(regressor.coef_)

0.9771801109127665
[1.35 0.85 1.31]
